es-tooling/module-replacements-codemods

- scripts/scaffold-codemod.js
When I used the scaffold script to generate files for the `array.prototype.map` package, it added this line to `index.js`
```js
import array.prototype.map from './array.prototype.map/index.js';
```
This PR fixes this. Now the generated code is valid js.
```js
import arrayPrototypeMap from './array.prototype.map/index.js';
```
> fix: scaffold script doesn't work for packages with dots in the name

- codemods/index.js
- codemods/object-keys/index.js
- codemods/shared.js
- test/fixtures/object-keys/case-1/after.js
- test/fixtures/object-keys/case-1/before.js
- test/fixtures/object-keys/case-1/result.js
- test/fixtures/object-keys/case-2/after.js
- test/fixtures/object-keys/case-2/before.js
- test/fixtures/object-keys/case-2/result.js
- test/fixtures/object-keys/case-3/after.js
- test/fixtures/object-keys/case-3/before.js
- test/fixtures/object-keys/case-3/result.js
- test/fixtures/object-keys/case-4/after.js
- test/fixtures/object-keys/case-4/before.js
- test/fixtures/object-keys/case-4/result.js
This adds a codemod replacement for the [`object-keys` module](https://www.npmjs.com/package/object-keys). This is my first time writing a codemod, so let me know if there's anything I can do to improve this code.
I've also added some improvements to the codebase that I think will be generally useful:
- Returned the identifier name from `removeImport` so that it will work even if the import is renamed to something than what is conventional
- Added some types to `removeImport`
> Add codemod to replace `object-keys`

- scripts/scaffold-codemod.js
Adds trailling commas to generated `codemods/index.js` file. This should align the style with the Biome configuration where trailing commas are enabled by default.
I noticed this small issue when I was resolving conflicts and I had to manually add the comma.
> style: add trailling comma option

- codemods/error-cause/index.js
- codemods/index.js
- codemods/shared.js
- test/fixtures/error-cause/case-1/after.js
- test/fixtures/error-cause/case-1/before.js
- test/fixtures/error-cause/case-1/result.js
Codemod for [`error-cause`](https://www.npmjs.com/package/error-cause), a package that polyfills the native [`Error.cause`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause) property, which has been available in all modern browsers and Node since ~2021.
It's not a particularly popular package, but just wanted to start with a simple codemod for my first contribution. Turned out to be worthwhile though because there wasn't an existing utility for removing side-effect `require`s, which is how `error-cause` injects its polyfill, so I added one.
Looking at the code, I think it's possible to polyfill individual error types, e.g. [`ReferenceError`](https://github.com/es-shims/error-cause/blob/792d2c6993c6bb6c47da52f3de2982c8cf98481c/ReferenceError/auto. …
> Add codemod for `error-cause` package

- codemods/index.js
- codemods/md5/index.js
- codemods/shared.js
- test/fixtures/md5/case-1/after.js
- test/fixtures/md5/case-1/before.js
- test/fixtures/md5/case-1/result.js
- test/fixtures/md5/case-2/after.js
- test/fixtures/md5/case-2/before.js
- test/fixtures/md5/case-2/result.js
- test/fixtures/md5/case-3/after.js
- test/fixtures/md5/case-3/before.js
- test/fixtures/md5/case-3/result.js
- test/fixtures/md5/case-4/after.js
- test/fixtures/md5/case-4/before.js
- test/fixtures/md5/case-4/result.js
Hi!
This PR replaces [md5](https://www.npmjs.com/package/md5) with the build-in `crypto` package. I'm using codemods and `jscodeshift` for the first time so I'd appreciate some feedback on the PR:
- It replaces `import md5 from 'md5'` successfully. What about `var md5 = require('md5');`? Do I need to handle this? Should this live in the same transformation file?
- What does `dirtyFlag` do?
- Should I transform to single or double quotes?
- Should I worry that this only works for node and not front end projects?
The replacement is based on [this](https://stackoverflow.com/questions/1655769/fastest-md5-implementation-in-javascript) SO answer. I also tested the generated code locally and it looks fine to me:
```bash
~/Development/node-playground> node md5-package.js …
```
> Replace md5 package

- codemods/array-buffer-byte-length/index.js
- codemods/index.js
- test/fixtures/array-buffer-byte-length/case-1/after.js
- test/fixtures/array-buffer-byte-length/case-1/before.js
- test/fixtures/array-buffer-byte-length/case-1/result.js
Codemod for [`array-buffer-byte-length`](https://www.npmjs.com/package/array-buffer-byte-length).
~I thought about abstracting some of the `ArrayBuffer` stuff into a shared util, but I think there's [only one other](https://github.com/es-tooling/module-replacements/blob/81e7dc647a208ed7e438b6e792a4150c8e0fff14/manifests/native.json#L251-L266) `ArrayBuffer` shim that needs a codemod, `arraybuffer.prototype.slice`, so I don't think it's worth it.~
**EDIT**: Actually, I think it could be worth adding utils like `transformInstanceMethod` and `transformInstanceProperty`. Would be useful for both `ArrayBuffer` and `TypedArray` codemods. I'll contribute them separately if they turn out to be useful.
I'll follow up with the `slice` codemod in a bit.
> Add codemod for `array-buffer-byte-length` package

- codemods/array.prototype.entries/index.js
- test/fixtures/array.prototype.entries/case-2/after.js
- test/fixtures/array.prototype.entries/case-2/before.js
- test/fixtures/array.prototype.entries/case-2/result.js
This PR fixes a bug in the `array.prototype.entries` codemod that attempts to substitute the `const entries = require('array.prototype.entries')` import with `[].entries()`. It incorrectly derives the name of the native `entries` method in the `Array` prototype from the name of the import identifier. Therefore if I import:
```js
const entries = require('array.prototype.entries')
```
My code becomes:
```js
[].arrayEntries()
```
This PR also adds a fixture to cover the non-standard import name case.
> fix: wrong substitution in `array.prototype.entries`

- codemods/is-builtin-module/index.js
- test/fixtures/is-builtin-module/case-2/after.js
- test/fixtures/is-builtin-module/case-2/before.js
- test/fixtures/is-builtin-module/case-2/result.js
- test/fixtures/is-builtin-module/case-3/after.js
- test/fixtures/is-builtin-module/case-3/before.js
- test/fixtures/is-builtin-module/case-3/result.js
This PR fixes two issues in the `is-builtin-module` codemod:
1. It doesn't work with non-standard import names. If you imported it like this:
```js
import banana from 'is-builtin-module';
```
The codemod would replace it with:
```js
import { isBuiltin } from "node:module";
```
But it wouldn't update the usages of the package, staying as `banana`. I've added a fixture under `case-2` to handle this.
1. It doesn't work with CJS. If used with a `require` call it would simply do nothing.
I've added a fixture under `case-3` to test that.
Note: I'm facing an issue here, see my comment below 👇
> fix: make `is-builtin-module` also support CJS + work with non-standard names

- codemods/object.hasown/index.js
- test/fixtures/object.hasown/case-1/after.js
- test/fixtures/object.hasown/case-1/before.js
- test/fixtures/object.hasown/case-1/result.js
Basically the same as the existing `hasown` but from `es-shims`.
I wonder if there is existing infrastructure to avoid duplicating codemods like this?
> feat: add `object.hasown`

- codemods/number.isfinite/index.js
- codemods/number.isinteger/index.js
- codemods/number.issafeinteger/index.js
- codemods/number.parsefloat/index.js
- codemods/number.parseint/index.js
- codemods/number.prototype.toexponential/index.js
- test/fixtures/number.isfinite/case-1/after.js
- test/fixtures/number.isfinite/case-1/before.js
- test/fixtures/number.isfinite/case-1/result.js
- test/fixtures/number.isinteger/case-1/after.js
- test/fixtures/number.isinteger/case-1/before.js
- test/fixtures/number.isinteger/case-1/result.js
- test/fixtures/number.issafeinteger/case-1/after.js
- test/fixtures/number.issafeinteger/case-1/before.js
- test/fixtures/number.issafeinteger/case-1/result.js
- test/fixtures/number.parsefloat/case-1/after.js
- test/fixtures/number.parsefloat/case-1/before.js
- test/fixtures/number.parsefloat/case-1/result.js
- test/fixtures/number.parseint/case-1/after.js
- test/fixtures/number.parseint/case-1/before.js
- test/fixtures/number.parseint/case-1/result.js
- test/fixtures/number.prototype.toexponential/case-1/after.js
- test/fixtures/number.prototype.toexponential/case-1/before.js
- test/fixtures/number.prototype.toexponential/case-1/result.js
Nothing much to do with those polyfills packages. Except removing the possible imports.
Luckily they're not popular _(based on downloads)_.
> feat: add codemods for `number.*` polyfills

- codemods/is-npm/index.js
- codemods/shared.js
- test/fixtures/is-npm/case-2/after.js
- test/fixtures/is-npm/case-2/before.js
- test/fixtures/is-npm/case-2/result.js
- test/fixtures/is-npm/case-3/after.js
- test/fixtures/is-npm/case-3/before.js
- test/fixtures/is-npm/case-3/result.js
- test/fixtures/is-npm/case-4/after.js
- test/fixtures/is-npm/case-4/before.js
- test/fixtures/is-npm/case-4/result.js
- test/fixtures/is-npm/case-5/after.js
- test/fixtures/is-npm/case-5/before.js
- test/fixtures/is-npm/case-5/result.js
Currently, the `is-npm` codemod assumes that developers name the imported members `isNpm`, `isYarn` and `isYarnOrNpm`. However, there are two ways in which developers could alter the imports that can't be handled by the codemod:
```js
// ESM
import { isNpm as banana, isYarn as pear, isNpmOrYarn as strawberry } from 'is-npm';
import * as banana from 'is-npm';
// CJS
const { isNpm: banana, isYarn: pear, isNpmOrYarn: strawberry } = require('is-npm');
const banana = require('is-npm');
```
Moreover, by relying on hardcoded names, we also could potentially make unsafe modifications to developer code (they could have an `isNpm` variable themselves which is different from the imported one and has a different meaning)
This PR makes the codemod detect the imported names dynamically so that it …
> fix(is-npm): support more ways of importing + non-standard import names

- codemods/es-define-property/index.js
- codemods/es-get-iterator/index.js
- codemods/es-set-tostringtag/index.js
- test/fixtures/es-define-property/case-1/after.js
- test/fixtures/es-define-property/case-1/before.js
- test/fixtures/es-define-property/case-1/result.js
- test/fixtures/es-get-iterator/case-1/after.js
- test/fixtures/es-get-iterator/case-1/before.js
- test/fixtures/es-get-iterator/case-1/result.js
- test/fixtures/es-set-tostringtag/case-1/after.js
- test/fixtures/es-set-tostringtag/case-1/before.js
- test/fixtures/es-set-tostringtag/case-1/result.js
Add the following codemods
- `es-get-iterator`
- `es-set-tostringtag`
- `es-define-property`
I'm not too familiar with `jscodeshift` so I'm not sure if there are problems with my codemods.
Also, I had some type errors. I'm not sure if this is expected or if it can be fixed
> feat: add codemods for `es-*`

- codemods/clone-regexp/index.js
- test/fixtures/clone-regexp/case-1/after.js
- test/fixtures/clone-regexp/case-1/before.js
- test/fixtures/clone-regexp/case-1/result.js
- test/fixtures/clone-regexp/case-2/after.js
- test/fixtures/clone-regexp/case-2/before.js
- test/fixtures/clone-regexp/case-2/result.js
- test/fixtures/clone-regexp/case-3/after.js
- test/fixtures/clone-regexp/case-3/before.js
- test/fixtures/clone-regexp/case-3/result.js
- test/fixtures/clone-regexp/case-4/after.js
- test/fixtures/clone-regexp/case-4/before.js
- test/fixtures/clone-regexp/case-4/result.js
Package: https://www.npmjs.com/package/clone-regexp
Weekly Downloads: 1,870,645
The function `cloneRegexp` cannot be directly replaced by `new RegExp` because of the `options` argument. Instead, I use the following logic
- Options are not given: Replace `cloneRegexp(regex)` with `new RegExp(regex)`
- Options are given: Replace `cloneRegexp(regex, opt)` with `new RegExp(regex) /* Todo /*` which makes the developer responsible of ensuring the new code isn't breaking.
> `clone-regexp`

- codemods/symbol.prototype.description/index.js
- test/fixtures/symbol.prototype.description/case-1/after.js
- test/fixtures/symbol.prototype.description/case-1/before.js
- test/fixtures/symbol.prototype.description/case-1/result.js
- test/fixtures/symbol.prototype.description/case-2/after.js
- test/fixtures/symbol.prototype.description/case-2/before.js
- test/fixtures/symbol.prototype.description/case-2/result.js
Module: [`symbol.prototype.description`](https://www.npmjs.com/package/symbol.prototype.description)
Weekly Downloads: 1,437,366
- Remove import
- Remove `description.shim()`
- Replace `description(Symbol('foo'))` with `Symbol('foo').description`
> `symbol.prototype.description`

- codemods/regexp.prototype.flags/index.js
- test/fixtures/regexp.prototype.flags/case-1/after.js
- test/fixtures/regexp.prototype.flags/case-1/before.js
- test/fixtures/regexp.prototype.flags/case-1/result.js
- test/fixtures/regexp.prototype.flags/case-2/after.js
- test/fixtures/regexp.prototype.flags/case-2/before.js
- test/fixtures/regexp.prototype.flags/case-2/result.js
- test/fixtures/regexp.prototype.flags/case-3/after.js
- test/fixtures/regexp.prototype.flags/case-3/before.js
- test/fixtures/regexp.prototype.flags/case-3/result.js
Package: [regexp.prototype.flags](https://www.npmjs.com/package/regexp.prototype.flags)
Weekly Downloads: 33,652,934
- Remove `import`/`require` statement
- Remove `flags.shim()`
- Replace `flags(arg)` with `arg.flags`
> `regexp.prototype.flags`

- codemods/es-shim-unscopables/index.js
- test/fixtures/es-shim-unscopables/case-1/after.js
- test/fixtures/es-shim-unscopables/case-1/before.js
- test/fixtures/es-shim-unscopables/case-1/result.js
- test/fixtures/es-shim-unscopables/case-2/after.js
- test/fixtures/es-shim-unscopables/case-2/before.js
- test/fixtures/es-shim-unscopables/case-2/result.js
Package [`es-shim-unscopables`](https://www.npmjs.com/package/es-shim-unscopables)
Weekly Downloads: 22,405,560
If I understood the package correctly, we just need to remove the import and any `shimUnscopables('...')` call.
> `es-shim-unscopables`

- codemods/es-string-html-methods/index.js
- test/fixtures/es-string-html-methods/case-1/after.js
- test/fixtures/es-string-html-methods/case-1/before.js
- test/fixtures/es-string-html-methods/case-1/result.js
- test/fixtures/es-string-html-methods/case-2/after.js
- test/fixtures/es-string-html-methods/case-2/before.js
- test/fixtures/es-string-html-methods/case-2/result.js
- test/fixtures/es-string-html-methods/case-3/after.js
- test/fixtures/es-string-html-methods/case-3/before.js
- test/fixtures/es-string-html-methods/case-3/result.js
Package: [`es-string-html-methods`](https://www.npmjs.com/package/es-string-html-methods)
Weekly Downloads: 654
Replace the following operations:
```javascript
[
'anchor',
'big',
'blink',
'bold',
'fixed',
'fontcolor',
'fontsize',
'italics',
'link',
'small',
'strike',
'sub',
'sup',
]
```
I had to use `//@ts-ignore` two times. I tried to add types but since those are JS files the linter did not allow it. What is the best way to resolve this?
> `es-string-html-methods`

- codemods/chalk/index.js
- index.js
- package-lock.json
- package.json
- test/fixtures/chalk/cjs/after.js
- test/fixtures/chalk/cjs/before.js
- test/fixtures/chalk/cjs/result.js
- test/fixtures/chalk/esm/after.js
- test/fixtures/chalk/esm/before.js
- test/fixtures/chalk/esm/result.js
Adds a codemod for moving from `chalk` to `picocolors`.
This will throw if exports are encountered which picocolors doesn't provide. For example, as of writing this, picocolors doesn't support bright colours (but soon will). That means `chalk.redBright` will throw since picocolors has no `redBright` export.
These patterns are supported:
```ts
// Before
chalk.red.bold(str);
// After
pc.red(pc.bold(str));
// Before
chalk.red`i am red`;
// After
pc.red(`i am red`);
// Before
chalk.red`i am red and ${chalk.bold('bold')}!`;
// After
pc.red(`i am red and ${pc.bold('bold')}!`);
```
Some patterns will not be detected. For example:
```ts
// Not detected since it isn't a call expression
chalk.red;
// Similarly not detected
const red = chalk.red;
red(str);
```
> feat: add chalk codemod

- codemods/deep-equal/index.js
- codemods/replaceImport.js
- index.js
- test/fixtures/deep-equal/cjs/after.js
- test/fixtures/deep-equal/cjs/before.js
- test/fixtures/deep-equal/cjs/result.js
- test/fixtures/deep-equal/esm-default/after.js
- test/fixtures/deep-equal/esm-default/before.js
- test/fixtures/deep-equal/esm-default/result.js
- test/fixtures/deep-equal/esm-namespace-assignment/after.js
- test/fixtures/deep-equal/esm-namespace-assignment/before.js
- test/fixtures/deep-equal/esm-namespace-assignment/result.js
- test/fixtures/deep-equal/esm-namespace-destructure/after.js
- test/fixtures/deep-equal/esm-namespace-destructure/before.js
- test/fixtures/deep-equal/esm-namespace-destructure/result.js
This adds a codemod for `deep-equal`. 
I also added a shared util for a generic `replaceImports` function, which can replace a module import as well as all of it's usages. This util should handle different ways of importing modules, as well as reassigning/destructuring imports outside of the initial import statement. For example:
```js
import * as module from 'deep-equal';
const foo = module.default;
foo('a', 'b');
```
This way future codemods can be implemented very easily based on this function, handling all the edge cases.
Right now the function doesn't handle scoping at all, so this will break:
```js
import deepEqual from 'deep-equal';
function maybeDeepEqual(deepEqual) {
deepEqual('a', 'b');
}
maybeDeepEqual(null);
```
I've implemented scope handling / binding tracking with babel …
> add deep-equal codemod

- scripts/which.js
I noticed the percentage is a bit off. The `which` script only lists native and micro-util replacements but there are preferred replacements in the package as well which counted towards the progress. What should the percentage represent? This PR uses native and micro-util replacements only.
> Fix progress indicator of `npm run which`

- package.json
Removes the postinstall script as it is currently failing and causing installs to fail.
> fix: remove postinstall script

- codemods/shared.js
- test/fixtures/array-every/imports-only/after.js
- test/fixtures/array-every/imports-only/before.js
- test/fixtures/array-every/imports-only/result.js
When using the `transformArrayMethod` helper, we currently only consider the change to be dirty if call expressions we mutated.
This means imports of these modules will not be removed unless there are also associated call expressions.
This fix simply considers removal of the import to be a dirty change.
Fixes #88
> fix: consider import removal to be dirty

- codemods/qs/index.js
- index.js
- test/fixtures/qs/basic/after.js
- test/fixtures/qs/basic/before.js
- test/fixtures/qs/basic/result.js
Adds a codemod for migrating from `qs` to `picoquery`.
Some options qs offers are not available. Currently, this mod will not warn on those but should in future.
Draft until we decide these things:
- should it throw when unknown/unsupported options are used?
- when `encode: false` is set, should we replace with `decodeURIComponent(stringify(obj))`? (`encode` is a pretty bad option to have so ideally we should just move consumers off it)
- there are some rarely used options like object sort functions etc that we shouldn't really try codemod. do we just throw when they're used?
> feat: add qs codemod

- codemods/object.assign/index.js
- codemods/shared.js
- index.js
- test/fixtures/object.assign/get-polyfill/after.js
- test/fixtures/object.assign/get-polyfill/before.js
- test/fixtures/object.assign/get-polyfill/result.js
- test/fixtures/object.assign/shim/after.js
- test/fixtures/object.assign/shim/before.js
- test/fixtures/object.assign/shim/result.js
- test/fixtures/object.assign/simple-cjs/after.js
- test/fixtures/object.assign/simple-cjs/before.js
- test/fixtures/object.assign/simple-cjs/result.js
- test/fixtures/object.assign/simple/after.js
- test/fixtures/object.assign/simple/before.js
- test/fixtures/object.assign/simple/result.js
- types/codemods/object.assign/index.d.ts
Adds a codemod for `object.assign`.
This also changes behaviour of `removeImport` to consider _all_ require calls with the target source, rather than only those which are directly call expressions.
> feat: add object.assign codemod

- codemods/iterate-value/index.js
- index.js
- test/fixtures/iterate-value/simple-cjs/after.js
- test/fixtures/iterate-value/simple-cjs/before.js
- test/fixtures/iterate-value/simple-cjs/result.js
- test/fixtures/iterate-value/simple/after.js
- test/fixtures/iterate-value/simple/before.js
- test/fixtures/iterate-value/simple/result.js
- types/codemods/iterate-value/index.d.ts
Adds a codemod for `iterate-value`.
This handles the following cases:
```ts
// with an inline arrow function (BEFORE)
iterate([], (v) => {});
// with an inline arrow function (AFTER)
for (const v of ([])) {};
// with a referenced function (BEFORE)
const fn = (v) => {};
iterate([], fn);
// with a referenced function (AFTER)
for (const value of ([])) { fn(value); };
// without a callback (BEFORE)
iterate([1, 1, 1]);
// without a callback (AFTER)
Array.from([1, 1, 1]);
```
the semi colon gets left behind on the `for` loops which feels awkward. however, i think people should be expected to run a formatter after using this codemod anyway since we're adding blocks of code rather than simple changes.
> feat: add iterate-value

- codemods/chalk/index.js
- test/fixtures/chalk/esm/after.js
- test/fixtures/chalk/esm/result.js
Currently we incorrectly import `picocolors` as if there's a default export:
```ts
import pc from 'picocolors';
```
This is incorrect since `picocolors` exports individual functions. So this fix will update it to the following:
```ts
import * as pc from 'picocolors';
```
> fix: always import picocolors as namespace

- codemods/rimraf/index.js
- index.js
- test/fixtures/rimraf/cjs/after.js
- test/fixtures/rimraf/cjs/before.js
- test/fixtures/rimraf/cjs/result.js
- test/fixtures/rimraf/esm/after.js
- test/fixtures/rimraf/esm/before.js
- test/fixtures/rimraf/esm/result.js
- test/fixtures/rimraf/legacy-cjs/after.js
- test/fixtures/rimraf/legacy-cjs/before.js
- test/fixtures/rimraf/legacy-cjs/result.js
- test/fixtures/rimraf/legacy-esm/after.js
- test/fixtures/rimraf/legacy-esm/before.js
- test/fixtures/rimraf/legacy-esm/result.js
Adds a new codemod to migrate from `rimraf`.
It will use `rm` or `rmSync` where appropriate.
If `glob` is set, it will use `tinyglobby` to find the files and later `rm` or `rmSync` them.
> feat: add rimraf codemod

- package.json
- scripts/generate-pkg-exports.js
Also adds the missing `.` export which broke in the last version.
> chore: update exports
